// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA3n8vvn4x62JvGC52NoDacDWygkahh7c',
    appId: '1:1004060174526:web:c764038a4ac510b54c56ef',
    messagingSenderId: '1004060174526',
    projectId: 'fir-xchat-69240',
    authDomain: 'fir-xchat-69240.firebaseapp.com',
    storageBucket: 'fir-xchat-69240.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhLLNzLW9YFFRFXUIFgy-Vbsgp_XIwD_M',
    appId: '1:1004060174526:android:af1a1d28d515f0514c56ef',
    messagingSenderId: '1004060174526',
    projectId: 'fir-xchat-69240',
    storageBucket: 'fir-xchat-69240.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFq9ikfcFMy-I2-KXn5xlq_IFU4xcS07k',
    appId: '1:1004060174526:ios:26f0e666433089cf4c56ef',
    messagingSenderId: '1004060174526',
    projectId: 'fir-xchat-69240',
    storageBucket: 'fir-xchat-69240.appspot.com',
    iosBundleId: 'com.example.firebasexchatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFq9ikfcFMy-I2-KXn5xlq_IFU4xcS07k',
    appId: '1:1004060174526:ios:26f0e666433089cf4c56ef',
    messagingSenderId: '1004060174526',
    projectId: 'fir-xchat-69240',
    storageBucket: 'fir-xchat-69240.appspot.com',
    iosBundleId: 'com.example.firebasexchatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA3n8vvn4x62JvGC52NoDacDWygkahh7c',
    appId: '1:1004060174526:web:5bee18d58a18cbca4c56ef',
    messagingSenderId: '1004060174526',
    projectId: 'fir-xchat-69240',
    authDomain: 'fir-xchat-69240.firebaseapp.com',
    storageBucket: 'fir-xchat-69240.appspot.com',
  );
}
